### ISSUE TITLE
How to run/write tests?

### ISSUE THREAD

**Issue by atugushev** [aohan237/asyncnsq#11]
Recently I've tried to write unit/integrational tests using `asyncnsq`, but had no luck. I've tried to borrow some tests from the repository, but It looks like the current tests don't work. I've got many import errors, it seems like tests are outdated.

Any plans on fixing tests and integrating tox/pytest/flake8/black/isort/pre-commit/ci which could make the project more friendly for the new contributors? I'd like to offer my help if you are interested.

**Comment by aohan237** [comment]
yeah, the tests is out of date .
it will be nice if you can help with the tests.

**Comment by atugushev** [comment]
I've made #12 for a start. Please review if you have time.

**Comment by aohan237** [comment]
will have updates for tests and examples
