### ISSUE TITLE
Question about _poll_lookupd() in consumer.py

### ISSUE THREAD

**Issue by Adzox** [aohan237/asyncnsq#2]
I was having a problem with my own codebase and was trying to see if the problem originated from this lib. The problem is when subscribing to a topic and channel when using a HTTP consumer, I get the following message:
`ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 4150)`
This seems to originate from the _poll_lookupd function in consumer.py:
```python
async def _poll_lookupd(self, host, port):
        nsqlookup_conn = NsqLookupd(host, port, loop=self._loop)
        try:
            res = await nsqlookup_conn.lookup(self.topic)
            logger.debug('lookupd response')
            logger.debug(res)
        except Exception as tmp:
            logger.error(tmp)
            logger.exception(tmp)

        for producer in res['producers']:
            host = '127.0.0.1' # Why localhost here?
            # producer['broadcast_address']
            port = producer['tcp_port']
            tmp_id = "tcp://{}:{}".format(host, port)
            if tmp_id not in self._connections:
                logger.debug(('host, port', host, port))
                conn = await create_nsq(host, port, queue=self._queue,
                                        loop=self._loop) # I get my error here
                logger.debug(('conn.id:', conn.id))
                self._connections[conn.id] = conn
                self._rdy_control.add_connection(conn)
await nsqlookup_conn.close()
```
So my real question is, should the connection be made to localhost, even though nsqlookupd in my case is running on a different server? Or am I missing something regarding NSQ?

Thanks in advance!

**Comment by Adzox** [comment]
Worthy note is that it is still possible to connect to nsqd via tcp (just verified that).

**Comment by aohan237** [comment]
@Adzox  if you want use http  ,you may use 4161 port which is the default http lookupd port by nsq

and lookupd will return your broadcast address other than ip address.

hope this will help you

you can refer to nsq.io for more information.

**Comment by Adzox** [comment]
I guess that's what the code above is for, but the broadcast address isn't used there? The above error was when using the HTTP port of the lookupd instance. Thanks for replying though, don't wanna let go of this lib :smiley:.

**Comment by aohan237** [comment]
@Adzox   just realize that this is a mistake when i get lazy to debug this lib ,which nsq server runs by docker.  

it is my mistake

the code : 
            host = '127.0.0.1' # Why localhost here?
            # producer['broadcast_address']
should not be 127.0.0.1, should be " host = producer['broadcast_address']"
i will fix it

thanks for your pointing it out

**Comment by Adzox** [comment]
It's A-OK, thanks for listening (reading, meh) :smile:

**Comment by Adzox** [comment]
I'll leave closing the issue to you xD Thansk for your help!

**Comment by aohan237** [comment]
👍  xD~
