### ISSUE TITLE
nsq conn运行一两天的样子就会自己关闭

### ISSUE THREAD

**Issue by inewlife** [aohan237/asyncnsq#6]
运行一两天后，asyncnsq.create_nsq_producer ，pub的时候没有错误信息输出，但是没有成功发送消息

**Comment by inewlife** [comment]
我注意到pub里面有注释掉这些代码，是不是这个导致的
if self._conn.closed:
            await self.reconnect()

**Comment by aohan237** [comment]
有个后台重连的任务再跑，定时会跑重连。所以，这段代码注释掉了，不然肯能会有短时间无限重连的问题。
发送结果 比如： data=writer.pub("aa").这个data是发送结果的返回值，查看一下是什么。
如果发送成功，结果应该是“OK”

**Comment by inewlife** [comment]
好的，谢谢，但是我现在发现那个后台的重连任务不会循环执行，可能是我对python的代码不熟的原因，有没有结合tornado使用的例子，创建了asyncnsq.create_nsq_producer对象

**Comment by inewlife** [comment]
找到原因了，我断开网络的时候self._status == consts.CLOSED这行代码中_status还是为2，所以不会重连

**Comment by inewlife** [comment]
async def reconnect(self):
        timeout_generator = retry_iterator(init_delay=0.1, max_delay=10.0)
        while True:
            if self._status == consts.CLOSED:
                print('_status closed and reconnect writer')
                try:
                    await self.close()
                    await self.connect()
                except ConnectionError:
                    logger.error("Can not connect to: {}:{} ".format(
                        self._host, self._port))
                else:
                    self._status = consts.CONNECTED
                t = next(timeout_generator)
            await asyncio.sleep(t, loop=self._loop)
上面代码的倒数第二行有缩进多了

**Comment by aohan237** [comment]
这个是ascynio从底层写的跟使用tornado的pynsq的客户端没有关系

想要用tornado可以参考一下，官方的pynsq的客户端。

另外， “我断开网络的时候self._status == consts.CLOSED这行代码中_status还是为2，所以不会重连”
这个意思是，你最开始说的，运行一两天时候的问题？
pub的返回值的日志有没有

**Comment by inewlife** [comment]
嗯，现在断线不会重连是两个原因导致的，
1.断开网络的时候self._status没有变成关闭状态
2.t = next(timeout_generator)缩进过多导致循环没有执行

**Comment by aohan237** [comment]
嗯。这两个问题已经修复。
你看一下还有没有别的问题

**Comment by inewlife** [comment]
暂时不知道我那个运行一两天发送不成功是不是这个原因导致的，我改了下日志输出，过一两天再看看

**Comment by aohan237** [comment]
不知道是否还出现过问题，如果没有问题，那么这个issue是否可以关闭了
