### ISSUE TITLE
how can i catch ConnectionResetError

### ISSUE THREAD

**Issue by xuxianren** [aohan237/asyncnsq#9]
when NSQ is restarted,  my app will never receive any more messages.

**Comment by aohan237** [comment]
can you show more infomation?
which version do you use? how do you restart the nsq?and is there any exception infomation?

**Comment by xuxianren** [comment]
the version is 1.0.1,  python version is 3.7.  os is win10
i run nsqd in cmd.  then i close the cmd. 
i can print the exc in connection.py line 196,  but when i try raise the exc in connection.py line 196, nothing happened
thank you very much and thank you can understand my poor english

`from asyncnsq import create_reader
import asyncio

loop = asyncio.get_event_loop()


async def go():
    try:
        reader = await create_reader(
            nsqd_tcp_addresses=['127.0.0.1:4150'],
            max_in_flight=200)
        await reader.subscribe('test_async_nsq', 'nsq')
        async for message in reader.messages():
            print(message.body)
            await message.fin()
    except Exception as tmp:
        print(type(tmp))


loop.run_until_complete(go())`


```
2019-01-03 11:22:16,259 - AsyncNsq - ERROR - 
[WinError 10054] 远程主机强迫关闭了一个现有的连接。
Traceback (most recent call last):
  File "C:\Users\XuDal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\asyncnsq\tcp\connection.py", line 190, in _read_data
    data = await self._reader.read(52)
  File "C:\Users\XuDal\AppData\Local\Programs\Python\Python37-32\lib\asyncio\streams.py", line 640, in read
    await self._wait_for_data('read')
  File "C:\Users\XuDal\AppData\Local\Programs\Python\Python37-32\lib\asyncio\streams.py", line 473, in _wait_for_data
    await self._waiter
  File "C:\Users\XuDal\AppData\Local\Programs\Python\Python37-32\lib\asyncio\selector_events.py", line 812, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] `远程主机强迫关闭了一个现有的连接。`
```

**Comment by aohan237** [comment]
没问题。我们可以用汉语。。
你把nsqd的cmd关了，就意味着nsq的服务器关了。
目前，reader还没有重连机制，writer有。

**Comment by xuxianren** [comment]
可以想象我知道你能用汉语的表情...

有什么方法可以在nsqd关闭时， 我程序也关闭吗？ 在196行可以捕获到异常， 我直接在196行那里sys.exit()?

**Comment by aohan237** [comment]
目前还没有提供这样的方法，一般来说，nsqd服务的稳定性远高于应用，所以这个需求大部分时间是不存在的。

以下方案并不推荐：
不过如果你要坚持，可以看一下reader._connections 这是个字典，里面key,value对应的是nsq的地址和tcp连接，可以检查一下里面的tcp连接的 _closed 的这个属性，可以检查到当前连接是否关闭，然后关闭当前的任务或者loop
